// Decompiled code from stars.exe (Stars! 2.60j RC3)
// Generated by Ghidra
// 

// ======================================================================
// Function: PszFormatIds
// Address: 1030:924c
// ======================================================================


char * __cdecl16far MSG::PszFormatIds(StringId ids,short *pParams)

{
  char *pcVar1;
  
  pcVar1 = STRINGS::PszGetCompressedString(ids);
  pcVar1 = PszFormatString(pcVar1,pParams);
  return pcVar1;
}



// ======================================================================
// Function: PszFormatString
// Address: 1030:85cc
// ======================================================================


/* WARNING: Could not reconcile some variable overlaps */

char * __cdecl16far MSG::PszFormatString(char *pszFormat,short *pParamsReal)

{
  char cVar1;
  short sVar2;
  int iVar3;
  char *pcVar4;
  ushort uVar5;
  int iVar6;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  bool bVar7;
  long lVar8;
  long lVar9;
  uint in_stack_0000fe00;
  uint uStack_1fe;
  uint uStack_1fc;
  SHDEF *lpshdef;
  char *pch;
  ushort w;
  char szBuf [480];
  char *pchT;
  short *pParams;
  short i;
  short c;
  short cOut;
  short iMineral;
  
  lVar9 = CONCAT22(unaff_SI,unaff_DI);
  iMineral = -1;
  pParams = pParamsReal;
  pch = (char *)c_common::szMsgBuf;
  do {
    if (*pszFormat == '\0') {
      *pch = '\0';
      return (char *)c_common::szMsgBuf;
    }
    if (*pszFormat != '\\') {
      *pch = *pszFormat;
      pch = pch + 1;
      goto LAB_1030_8f4d;
    }
    pszFormat = pszFormat + 1;
    iVar6 = *pszFormat + -0x45;
    bVar7 = iVar6 < 0;
    iVar3 = (int)pParams;
    switch(iVar6) {
    case 0:
      pchT = PLANET::PszCalcEnvVar((uint)*pParams >> 8,*pParams & 0xff);
      break;
    case 1:
      pchT = UTIL::PszFleetNameFromWord(*pParams);
      break;
    case 2:
      w = *pParams;
      sVar2 = UTILGEN::CchGetString(w + idsMineField,pch);
      pch = pch + sVar2;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      goto LAB_1030_8f4d;
    default:
      *pch = *pszFormat;
      pch = pch + 1;
      goto LAB_1030_8f4d;
    case 4:
      pchT = STRINGS::PszGetCompressedString(*pParams + idsDecreased);
      break;
    case 7:
    case 0x27:
      pchT = UTIL::PszPlayerName(*pParams & 0xf,(uint)(*pszFormat == 'L'),
                                 (uint)((*pParams & 0x10U) != 0),(uint)((*pParams & 0x20U) != 0),
                                 (int)(*pParams & 0xc0U) >> 6,(PLAYER *)0x0);
      break;
    case 8:
      pchT = *(char **)(*pParams * 2 + 0x4f2);
      break;
    case 10:
      w = (uint)*pParams >> 9 & 0xf;
      pchT = UTIL::PszPlayerName(w,0,0,0,0,(PLAYER *)0x0);
      break;
    case 0xb:
      uStack_1fe = *pParams / 100;
      uStack_1fc = (int)uStack_1fe >> 0xf;
      PUBLIC::__aFfcompp();
      if (bVar7) {
        c = _WSPRINTF((LPSTR)CONCAT13((char)((uint)(*pParams / 100) >> 8),
                                      CONCAT12((char)(*pParams / 100),0x1120)),
                      (LPCSTR)CONCAT22(_DATA::PCTDXPCTDPCTPCT,0x1120),pch);
      }
      else {
        c = _WSPRINTF((LPSTR)CONCAT22(*pParams / 100,0x1120),
                      (LPCSTR)CONCAT22(_DATA::PCTDPCTPCT,0x1120),pch);
      }
      pch = pch + c;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      goto LAB_1030_8f4d;
    case 0xe:
      if (*pParams != _DATA::idPlayer) {
        UTILGEN::CchGetString(idsOf2,szBuf);
        pcVar4 = UTIL::PszPlayerName(*pParams,0,0,0,0,(PLAYER *)0x0);
        PUBLIC::_strcat(szBuf,pcVar4);
        pcVar4 = STRINGS::PszGetCompressedString(idsOrigin);
        PUBLIC::_strcat(szBuf,pcVar4);
        pchT = szBuf;
        break;
      }
      goto MSG_DoNothing;
    case 0x10:
    case 0x11:
    case 0x31:
      uStack_1fe = *pParams;
      uStack_1fc = 0;
      lVar8 = PUBLIC::__aFlshl(lVar9,in_stack_0000fe00);
      lpshdef._0_2_ = (uint)lVar8 | uStack_1fe;
      lpshdef._2_2_ = (uint)((ulong)lVar8 >> 0x10) | uStack_1fc;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 4);
      iVar3 = _WSPRINTF((LPSTR)CONCAT13((char)((uint)lpshdef >> 8),
                                        CONCAT12((char)(uint)lpshdef,0x1120)),
                        (LPCSTR)CONCAT22(_DATA::PCTLD,0x1120),pch);
      pch = pch + iVar3;
      if (*pszFormat != 'v') {
        if (*pszFormat == 'V') {
          iMineral = *pParams;
        }
        pcVar4 = *(char **)(iMineral * 2 + 0xb48);
        PUBLIC::_strcpy(pch,pcVar4);
        uVar5 = PUBLIC::_strlen(pcVar4);
        pch = pch + uVar5;
      }
      goto LAB_1030_8f4d;
    case 0x13:
      goto MSG_DoNothing;
    case 0x15:
      w = *pParams;
      if (w != 0) {
        if ((w - 1 & w) == 0) {
          c = 0;
          for (; (w & 1) == 0; w = w >> 1) {
            c = c + 1;
          }
          pchT = UTIL::PszPlayerName(c,0,1,1,0,(PLAYER *)0x0);
          break;
        }
        cOut = 0;
        for (i = 0; i < _DATA::game.cPlayer; i = i + 1) {
          if ((w & 1) != 0) {
            if (0 < cOut) {
              if ((w & 0xfffe) == 0) {
                sVar2 = UTILGEN::CchGetString(idsAnd,pch);
                pch = pch + sVar2;
              }
              else {
                pcVar4 = pch + 1;
                *pch = ',';
                pch = pch + 2;
                *pcVar4 = ' ';
              }
            }
            pcVar4 = UTIL::PszPlayerName(i,0,1,1,0,(PLAYER *)0x0);
            PUBLIC::_strcpy(pch,pcVar4);
            uVar5 = PUBLIC::_strlen(pcVar4);
            pch = pch + uVar5;
            cOut = cOut + 1;
          }
          w = w >> 1;
        }
        goto MSG_DoNothing;
      }
      goto LAB_1030_8f4d;
    case 0x20:
      pchT = *(char **)(*pParams * 2 + 0x47e);
      break;
    case 0x21:
    case 0x23:
    case 0x2d:
    case 0x2f:
    case 0x34:
      PUBLIC::_strcpy(pch,(char *)c_common::szBase);
      uVar5 = PUBLIC::_strlen((char *)c_common::szBase);
      pch = pch + uVar5;
      cVar1 = *pszFormat;
      if (cVar1 == 'f') {
        if (_DATA::idPlayer == -1) {
LAB_1030_86a2:
          if (_DATA::idPlayer == -1) goto LAB_1030_86d0;
          c = _WSPRINTF((LPSTR)CONCAT22(_DATA::idPlayer + 1,0x1120),(LPCSTR)0xb591120,pch);
        }
        else {
          c = _WSPRINTF((LPSTR)CONCAT22(_DATA::idPlayer + 1,0x1120),(LPCSTR)0xb541120,pch);
        }
        goto MSG_DoInt;
      }
      if (cVar1 == 'h') {
LAB_1030_86d0:
        PUBLIC::_strcat(pch,(char *)0xb5e);
        pch = pch + 4;
      }
      else {
        if (cVar1 == 'r') {
          c = _WSPRINTF((LPSTR)CONCAT22(_DATA::idPlayer + 1,0x1120),(LPCSTR)0xb631120,pch);
          goto MSG_DoInt;
        }
        if (cVar1 == 't') goto LAB_1030_86a2;
        if (cVar1 == 'y') {
          PUBLIC::_strcat(pch,(char *)0xb68);
          pch = pch + 3;
        }
      }
      goto LAB_1030_8f4d;
    case 0x22:
MSG_LThingName:
      pchT = UTIL::PszGetThingName(*pParams);
      break;
    case 0x24:
      c = _WSPRINTF((LPSTR)CONCAT22(*pParams,0x1120),(LPCSTR)CONCAT22(_DATA::PCTD,0x1120),pch);
MSG_DoInt:
      pch = pch + c;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      goto LAB_1030_8f4d;
    case 0x25:
      pchT = STRINGS::PszGetCompressedString(*pParams + idsEnergy);
      break;
    case 0x26:
      uStack_1fe = *pParams;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      in_stack_0000fe00 = *pParams;
      uStack_1fc = uStack_1fc & 0xff00 | in_stack_0000fe00 & 0xff;
      PARTS::FLookupPart((PART *)&stack0xfe02);
      PUBLIC::__fstrcpy((char *)CONCAT22(0x1120,pch),
                        (char *)CONCAT22(lpshdef._2_2_,(uint)lpshdef + 8));
      uVar5 = PUBLIC::__fstrlen((char *)CONCAT22(lpshdef._2_2_,(uint)lpshdef + 8));
      pch = pch + uVar5;
      pParams = (short *)CONCAT22(pParams._2_2_,iVar3 + 4);
      goto LAB_1030_8f4d;
    case 0x28:
      iMineral = *pParams;
      pchT = *(char **)(iMineral * 2 + 0x4cc);
      break;
    case 0x29:
      if (*pParams == -2) {
        pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
        goto MSG_LThingName;
      }
      if (*pParams == -1) {
        pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
        goto switchD_1030_8edc_caseD_2a;
      }
      pchT = UTIL::PszGetLocName(grobjNone,-1,*pParams,*(short *)((int)pParams + 2));
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      break;
    case 0x2a:
switchD_1030_8edc_caseD_2a:
      if ((*pParams & 0x8000U) != 0) goto MSG_DoFleet;
    case 0x2b:
      pchT = UTIL::PszGetPlanetName(*pParams);
      break;
    case 0x2e:
MSG_DoFleet:
      w = *pParams | 0x8000;
      pchT = UTIL::PszGetFleetName(w);
      break;
    case 0x30:
      iVar3 = _WSPRINTF((LPSTR)CONCAT22(*pParams,0x1120),(LPCSTR)0xb6c1120,pch);
      pch = pch + iVar3;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      goto LAB_1030_8f4d;
    case 0x32:
      PUBLIC::_strcpy(pch,(char *)c_common::szWork);
      uVar5 = PUBLIC::_strlen((char *)c_common::szWork);
      pch = pch + uVar5;
      goto LAB_1030_8f4d;
    case 0x35:
      iVar3 = *pParams >> 5;
      w = *pParams & 0x1f;
      if (w < 0x10) {
        lpshdef._2_2_ = *(uint *)(iVar3 * 4 + 0x100);
        lpshdef._0_2_ = *(int *)(iVar3 * 4 + 0xfe) + w * 0x93;
      }
      else {
        lpshdef._2_2_ = *(uint *)(iVar3 * 4 + 0x14e);
        lpshdef._0_2_ = *(int *)(iVar3 * 4 + 0x14c) + (w - 0x10) * 0x93;
      }
      if (iVar3 == _DATA::idPlayer) {
        PUBLIC::__fstrcpy((char *)CONCAT22(0x1120,pch),
                          (char *)CONCAT22(lpshdef._2_2_,(uint)lpshdef + 8));
      }
      else {
        pcVar4 = UTIL::PszPlayerName(iVar3,0,0,1,0,(PLAYER *)0x0);
        _WSPRINTF((LPSTR)CONCAT22(pcVar4,0x1120),(LPCSTR)0xb6f1120,pch);
      }
      uVar5 = PUBLIC::_strlen(pch);
      pch = pch + uVar5;
      pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
      goto LAB_1030_8f4d;
    }
    PUBLIC::_strcpy(pch,pchT);
    uVar5 = PUBLIC::_strlen(pchT);
    pch = pch + uVar5;
MSG_DoNothing:
    pParams = (short *)CONCAT22(pParams._2_2_,(int)pParams + 2);
LAB_1030_8f4d:
    pszFormat = pszFormat + 1;
  } while( true );
}



// ======================================================================
// Function: PszPlayerName
// Address: 1038:11f2
// ======================================================================


char * __cdecl16far
UTIL::PszPlayerName(short iPlayer,short fCapital,short fPlural,short fThe,short grWord,PLAYER *pplr)

{
  int iVar1;
  char *pcVar2;
  ushort uVar3;
  undefined2 unaff_SS;
  char szName [50];
  char *pchEnd;
  
  if (pplr == (PLAYER *)0x0) {
    pplr = (PLAYER *)((int)c_common::rgplr + iPlayer * 0xc0);
  }
  if (pplr->szName[0] == '\0') {
    iVar1 = iPlayer + 1;
    pcVar2 = STRINGS::PszGetCompressedString(idsPlayerD2);
    _WSPRINTF((LPSTR)CONCAT22(iVar1,0x1120),(LPCSTR)CONCAT22(pcVar2,unaff_SS),szName);
    if (fPlural == 0) {
      PUBLIC::_strcat(szName,(char *)0x515);
    }
    if (grWord == 1) {
      uVar3 = PUBLIC::_strlen(szName);
      UTILGEN::CchGetString(idsHas,szName + uVar3);
    }
    else if (grWord == 2) {
      uVar3 = PUBLIC::_strlen(szName);
      UTILGEN::CchGetString(idsIs2,szName + uVar3);
    }
  }
  else {
    if (fThe == 0) {
      szName[0] = '\0';
    }
    else {
      PUBLIC::_strcpy(szName,(char *)0x50e);
      if (fCapital != 0) {
        szName[0] = 'T';
      }
    }
    if ((fPlural == 0) || (pplr->szNames[0] == '\0')) {
      PUBLIC::_strcat(szName,pplr->szName);
    }
    else {
      PUBLIC::_strcat(szName,pplr->szNames);
    }
    uVar3 = PUBLIC::_strlen(szName);
    pchEnd = szName + (uVar3 - 1);
    while ((*pchEnd == ' ' && (szName <= pchEnd))) {
      *pchEnd = '\0';
      pchEnd = pchEnd + -1;
    }
    if (pchEnd < szName) {
      UTILGEN::CchGetString(idsName,szName);
    }
    if ((fPlural != 0) && (pplr->szNames[0] == '\0')) {
      uVar3 = PUBLIC::_strlen(szName);
      if ((szName[uVar3 - 1] != 's') && ((szName[uVar3 - 1] != 'e' || (szName[uVar3 - 2] != 's'))))
      {
        PUBLIC::_strcat(szName,(char *)0x513);
      }
    }
    if (grWord == 1) {
      uVar3 = PUBLIC::_strlen(szName);
      UTILGEN::CchGetString(idsHave2,szName + uVar3);
    }
    else if (grWord == 2) {
      uVar3 = PUBLIC::_strlen(szName);
      UTILGEN::CchGetString(idsAre,szName + uVar3);
    }
  }
  PUBLIC::_strcpy((char *)c_common::szWork,szName);
  return (char *)c_common::szWork;
}



// ======================================================================
// Function: PszGetPlanetName
// Address: 1038:2c6a
// ======================================================================


char * __cdecl16far UTIL::PszGetPlanetName(short id)

{
  char *pcVar1;
  char *pcVar2;
  char *psz;
  short fInOrbit;
  
  pcVar1 = UTILGEN::PszGetCompressedPlanet(*(short *)((int)c_common::rgidPlan + id * 2));
  if ((id & 0x8000U) == 0) {
    PUBLIC::_strcpy((char *)c_common::szWork,pcVar1);
  }
  else {
    pcVar2 = STRINGS::PszGetCompressedString(idsOrbitingS);
    _WSPRINTF((LPSTR)CONCAT22(pcVar1,0x1120),(LPCSTR)CONCAT22(pcVar2,0x1120),(int)c_common::szWork);
  }
  return (char *)c_common::szWork;
}



// ======================================================================
// Function: PszGetFleetName
// Address: 1038:292c
// ======================================================================


/* WARNING: Variable defined which should be unmapped: lpsz */

char * __cdecl16far UTIL::PszGetFleetName(short id)

{
  int iVar1;
  uint iPlayer;
  char *pcVar2;
  short sVar3;
  int iVar4;
  undefined2 unaff_SS;
  FLEET *lpfl_00;
  short cch;
  short ishdef;
  char szPlr [34];
  FLEET *lpfl;
  short ifl;
  char szShdef [34];
  char *lpsz;
  short iplr;
  short cshdef;
  
  lpfl_00 = LpflFromId(id & 0x7fff);
  iVar4 = (int)((ulong)lpfl_00 >> 0x10);
  iVar1 = (int)lpfl_00;
  iPlayer = (id & 0x7fffU) >> 9 & 0xf;
  if (iPlayer == _DATA::idPlayer) {
    szPlr[0] = '\0';
  }
  else {
    pcVar2 = PszPlayerName(iPlayer,0,0,0,0,(PLAYER *)0x0);
    _WSPRINTF((LPSTR)CONCAT22(pcVar2,0x1120),(LPCSTR)CONCAT22(0x520,unaff_SS),szPlr);
  }
  if (((iVar1 == 0) && (iVar4 == 0)) ||
     ((*(int *)(iVar1 + 0x78) == 0 && (*(int *)(iVar1 + 0x7a) == 0)))) {
    if ((iVar1 == 0) && (iVar4 == 0)) {
      STRINGS::PszGetCompressedString(idsFleet);
    }
    else {
      sVar3 = IshdefPrimaryFromLpfl(lpfl_00,&cshdef);
      if (sVar3 == 0x10) {
        STRINGS::PszGetCompressedString(idsFleet);
      }
      else {
        PUBLIC::__fstrcpy((char *)CONCAT22(unaff_SS,szShdef),
                          (char *)CONCAT22(*(undefined2 *)(iPlayer * 4 + 0x100),
                                           *(int *)(iPlayer * 4 + 0xfe) + sVar3 * 0x93 + 8));
        cch = PUBLIC::_strlen(szShdef);
        if (0x1c < cch) {
          cch = 0x1c;
        }
        if (1 < cshdef) {
          szShdef[cch] = '+';
          szShdef[cch + 1] = '\0';
        }
      }
    }
    _WSPRINTF((LPSTR)CONCAT22(szPlr,0x1120),(LPCSTR)0x5291120,(int)c_common::szWork);
  }
  else {
    _WSPRINTF((LPSTR)CONCAT22(szPlr,0x1120),(LPCSTR)0x5241120,(int)c_common::szWork);
  }
  return (char *)c_common::szWork;
}



// ======================================================================
// Function: LpflFromId
// Address: 1038:2078
// ======================================================================


FLEET * __stdcall16far UTIL::LpflFromId(short idFleet)

{
  int iVar1;
  int iVar2;
  int *piVar3;
  int *piVar4;
  int **ppiVar5;
  short iHi;
  short iplrCur;
  FLEET *lpfl;
  short i;
  short iGuess;
  short iLo;
  short idGuess;
  short iplr;
  
  i = 0;
  for (iplrCur = 0; iplrCur < (int)((uint)idFleet >> 9 & 0xf); iplrCur = iplrCur + 1) {
    i = i + (*(uint *)((int)&c_common::rgplr[0].flags3 + iplrCur * 0xc0) & 0xfff);
  }
  iHi = c_common::cFleet;
  iVar2 = i + -1;
  do {
    iLo = iVar2;
    if (iHi <= iLo + 1) {
      piVar3 = (int *)0x0;
      piVar4 = (int *)0x0;
      break;
    }
    iVar2 = iLo + iHi >> 1;
    ppiVar5 = (int **)((int)_DATA::rglpfl + iVar2 * 4);
    piVar3 = *ppiVar5;
    piVar4 = ppiVar5[1];
    iVar1 = *piVar3;
  } while ((iVar1 < (int)(idFleet & 0x1fffU)) ||
          (iHi = iVar2, iVar2 = iLo, (int)(idFleet & 0x1fffU) < iVar1));
  return (FLEET *)CONCAT22(piVar4,piVar3);
}



// ======================================================================
// Function: IshdefPrimaryFromLpfl
// Address: 1038:3e1c
// ======================================================================


short __cdecl16far UTIL::IshdefPrimaryFromLpfl(FLEET *lpfl,short *pcDiff)

{
  int *piVar1;
  int iVar2;
  short ihul;
  short csh;
  short i;
  short ish;
  short cDiff;
  
  cDiff = 0;
  csh = 0;
  ish = 0x10;
  for (i = 0; i < 0x10; i = i + 1) {
    if ((0 < *(int *)((int)lpfl + 0xc + i * 2)) &&
       (cDiff = cDiff + 1, piVar1 = (int *)((int)lpfl + 0xc + i * 2),
       *piVar1 != csh && csh <= *piVar1)) {
      ish = i;
      csh = *(int *)((int)lpfl + 0xc + i * 2);
      iVar2 = *(int *)((int)lpfl + 2) * 4;
      iVar2 = *(int *)(*(int *)(iVar2 + 0xfe) + i * 0x93);
      if ((iVar2 == 0x19) || (iVar2 == 0x1a)) {
        csh = csh + -1;
      }
    }
  }
  if (pcDiff != (short *)0x0) {
    *pcDiff = cDiff;
  }
  return ish;
}



// ======================================================================
// Function: PszFleetNameFromWord
// Address: 1038:2b5e
// ======================================================================


/* WARNING: Variable defined which should be unmapped: lpsz */
/* WARNING: Could not reconcile some variable overlaps */

char * __cdecl16far UTIL::PszFleetNameFromWord(ushort w)

{
  uint uVar1;
  undefined2 unaff_SS;
  short cch;
  short ishdef;
  char szShdef [34];
  char *lpsz;
  
  uVar1 = w >> 9 & 0xf;
  if ((*(uint *)(*(int *)(_DATA::idPlayer * 4 + 0xfe) + uVar1 * 0x93 + 0x7b) >> 9 & 1) == 0) {
    PUBLIC::__fstrcpy((char *)CONCAT22(unaff_SS,szShdef),
                      (char *)CONCAT22(*(undefined2 *)(_DATA::idPlayer * 4 + 0x100),
                                       *(int *)(_DATA::idPlayer * 4 + 0xfe) + uVar1 * 0x93 + 8));
    cch = PUBLIC::_strlen(szShdef);
    if (0x1c < cch) {
      cch = 0x1c;
    }
    if ((w & 0x2000) != 0) {
      szShdef[cch] = '+';
      szShdef[cch + 1] = '\0';
    }
    lpsz._0_2_ = szShdef;
  }
  else {
    lpsz._0_2_ = STRINGS::PszGetCompressedString(idsFleet);
  }
  _WSPRINTF((LPSTR)CONCAT22((char *)lpsz,0x1120),(LPCSTR)0x5321120,(int)c_common::szWork);
  return (char *)c_common::szWork;
}



// ======================================================================
// Function: PszGetThingName
// Address: 1038:26de
// ======================================================================


char * __cdecl16far UTIL::PszGetThingName(short id)

{
  char *pcVar1;
  char *pcVar2;
  int iVar3;
  undefined2 unaff_SS;
  THING *pTVar4;
  char szPlr [54];
  THING *lpth;
  
  pTVar4 = LpthFromId(id);
  iVar3 = (int)((ulong)pTVar4 >> 0x10);
  if (((int)pTVar4 == 0) && (iVar3 == 0)) {
    c_common::szWork[0] = '\0';
  }
  else if ((uint)pTVar4->flags1 >> 0xd == 0) {
    if (((uint)pTVar4->flags1 >> 9 & 0xf) == _DATA::idPlayer) {
      szPlr[0] = '\0';
    }
    else {
      pcVar2 = PszPlayerName((uint)pTVar4->flags1 >> 9 & 0xf,0,0,0,0,(PLAYER *)0x0);
      _WSPRINTF((LPSTR)CONCAT22(pcVar2,0x1120),(LPCSTR)CONCAT22(0x518,unaff_SS),szPlr);
    }
    pcVar2 = szPlr;
    pcVar1 = STRINGS::PszGetCompressedString(idsSSMineField);
    _WSPRINTF((LPSTR)CONCAT22(pcVar2,0x1120),(LPCSTR)CONCAT22(pcVar1,0x1120),(int)c_common::szWork);
  }
  else if ((uint)pTVar4->flags1 >> 0xd == 1) {
    if ((*(uint *)((int)pTVar4 + 6) >> 10 & 0xf) == 0) {
      UTILGEN::CchGetString(idsSalvage,(char *)c_common::szWork);
    }
    else {
      if (((uint)pTVar4->flags1 >> 9 & 0xf) == _DATA::idPlayer) {
        szPlr[0] = '\0';
      }
      else {
        pcVar2 = PszPlayerName((uint)pTVar4->flags1 >> 9 & 0xf,0,0,0,0,(PLAYER *)0x0);
        _WSPRINTF((LPSTR)CONCAT22(pcVar2,0x1120),(LPCSTR)CONCAT22(0x51c,unaff_SS),szPlr);
      }
      pcVar2 = szPlr;
      pcVar1 = STRINGS::PszGetCompressedString(idsSmineralPacket);
      _WSPRINTF((LPSTR)CONCAT22(pcVar2,0x1120),(LPCSTR)CONCAT22(pcVar1,0x1120),(int)c_common::szWork
               );
    }
  }
  else if ((uint)pTVar4->flags1 >> 0xd == 2) {
    pcVar2 = STRINGS::PszGetCompressedString(idsWormhole);
    PUBLIC::_strcpy((char *)c_common::szWork,pcVar2);
  }
  else if ((uint)pTVar4->flags1 >> 0xd == 3) {
    pcVar2 = STRINGS::PszGetCompressedString(idsMysteryTrader);
    PUBLIC::_strcpy((char *)c_common::szWork,pcVar2);
  }
  else {
    pcVar2 = STRINGS::PszGetCompressedString(idsMysteryObject);
    PUBLIC::_strcpy((char *)c_common::szWork,pcVar2);
  }
  return (char *)c_common::szWork;
}



// ======================================================================
// Function: LpthFromId
// Address: 1038:01b2
// ======================================================================


/* WARNING: Could not reconcile some variable overlaps */

THING * __stdcall16far UTIL::LpthFromId(short idth)

{
  THING *lpthMac;
  THING *lpth;
  
  lpth = (THING *)CONCAT22(_DATA::lpThings._2_2_,(int)_DATA::lpThings);
  while ((uint)lpth < (uint)((int)_DATA::lpThings + _DATA::cThing * 0x12)) {
    if (lpth->flags1 == idth) goto LAB_1038_0218;
    lpth = (THING *)CONCAT22(lpth._2_2_,(uint)lpth + 0x12);
  }
  lpth._0_2_ = 0;
  lpth._2_2_ = 0;
LAB_1038_0218:
  return (THING *)CONCAT22(lpth._2_2_,(uint)lpth);
}



// ======================================================================
// Function: PszGetLocName
// Address: 1038:3b08
// ======================================================================


char * __cdecl16far UTIL::PszGetLocName(GrobjClass grobj,short id,short x,short y)

{
  char *pcVar1;
  
  if (id != -1) {
    if (grobj == grobjPlanet) {
      pcVar1 = PszGetPlanetName(id);
      return pcVar1;
    }
    if (grobj == grobjFleet) {
      pcVar1 = PszGetFleetName(id);
      return pcVar1;
    }
    if (grobj == grobjThing) {
      pcVar1 = PszGetThingName(id);
      return pcVar1;
    }
  }
  if ((x == -1) && (y == -1)) {
    pcVar1 = STRINGS::PszGetCompressedString(idsDeepSpace);
    PUBLIC::_strcpy((char *)c_common::szWork,pcVar1);
  }
  else {
    pcVar1 = STRINGS::PszGetCompressedString(idsSpaceDD);
    _WSPRINTF((LPSTR)CONCAT22(x,0x1120),(LPCSTR)CONCAT22(pcVar1,0x1120),(int)c_common::szWork);
  }
  return (char *)c_common::szWork;
}



