// Decompiled code from stars.exe (Stars! 2.60j RC3)
// Generated by Ghidra
// 

// ======================================================================
// Function: LdpFromItokDv
// Address: 10e8:07a8
// ======================================================================


/* WARNING: Could not reconcile some variable overlaps */

int __cdecl16far VCR::LdpFromItokDv(int itok,short *lpdv)

{
  undefined2 uVar1;
  int iVar2;
  SHDEF *pSVar3;
  undefined4 uVar4;
  undefined2 uVar5;
  undefined2 uVar6;
  undefined4 uVar7;
  long dp;
  short csh;
  ushort dpShdef;
  DV dv;
  
  if (((int)lpdv == 0) && (lpdv._2_2_ == 0)) {
    dv.flags1 = 0;
  }
  else {
    dv.flags1 = *lpdv;
  }
  pSVar3 = BATTLE::LpshdefFromTok
                     ((TOK *)CONCAT22(c_common::vrgtok._2_2_,(int)c_common::vrgtok + itok * 0x1d));
  uVar1 = *(undefined2 *)((int)pSVar3 + 0x38);
  dp._0_2_ = PUBLIC::__aFulmul(uVar1,0,*(undefined2 *)((int)c_common::vrgtok + itok * 0x1d + 0x13),0
                              );
  if (dv.flags1 != 0) {
    uVar7 = 100;
    uVar4 = PUBLIC::__aFulmul(*(undefined2 *)((int)c_common::vrgtok + itok * 0x1d + 0x13),0,
                              dv.flags1 & 0x7f,0);
    csh = PUBLIC::__aFldiv(uVar4,uVar7);
    if (csh < 1) {
      csh = 1;
    }
    uVar7 = 0x32;
    iVar2 = csh >> 0xf;
    uVar6 = 0;
    uVar5 = 10;
    uVar4 = PUBLIC::__aFulmul(uVar1,0,(uint)dv.flags1 >> 7,0);
    uVar4 = PUBLIC::__aFldiv(uVar4,uVar5,uVar6);
    uVar4 = PUBLIC::__aFulmul(uVar4,csh,iVar2);
    iVar2 = PUBLIC::__aFldiv(uVar4,uVar7);
    dp._0_2_ = (int)dp - iVar2;
  }
  return (int)dp;
}



// ======================================================================
// Function: GetVCRStats
// Address: 10e8:193e
// ======================================================================


/* WARNING: Could not reconcile some variable overlaps */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16far VCR::GetVCRStats(short itok,long *pdpArmor,DV *pdv,long *pdpShields,short *pcsh)

{
  undefined2 uVar1;
  uint uVar2;
  undefined2 *puVar3;
  int iVar4;
  undefined2 uVar5;
  bool bVar6;
  SHDEF *pSVar7;
  long lVar8;
  undefined4 uVar9;
  long lVar10;
  undefined4 uVar11;
  undefined2 uVar12;
  undefined4 uVar13;
  ushort dpShdef;
  short cshKill;
  short i;
  long dpArmor;
  long dpShields;
  DV dv;
  short cshT;
  
  dpShields._0_2_ = 0;
  dpShields._2_2_ = 0;
  cshKill = 0;
  dv.flags1 = -1;
  puVar3 = (undefined2 *)((int)_DATA::vrgdpVCR + itok * 4);
  uVar1 = *puVar3;
  uVar12 = puVar3[1];
  lVar8 = CONCAT22(uVar12,uVar1);
  i = 0;
  while( true ) {
    uVar11 = CONCAT22(dpShields._2_2_,(uint)dpShields);
    uVar5 = (undefined2)((ulong)_vlpbrVCR >> 0x10);
    iVar4 = (int)_vlpbrVCR;
    if (*(int *)(iVar4 + 2) <= i) break;
    if ((uint)*(byte *)(iVar4 + 6 + i * 8) == itok) {
      cshKill = cshKill + *(int *)(iVar4 + i * 8 + 8);
      iVar4 = 0;
      uVar2 = PUBLIC::__aFlshl();
      bVar6 = CARRY2((uint)dpShields,uVar2);
      dpShields._0_2_ = (uint)dpShields + uVar2;
      dpShields._2_2_ = dpShields._2_2_ + iVar4 + (uint)bVar6;
      dv.flags1 = *(short *)(c_common::vlpbrVCR + i * 8 + 0xc);
    }
    i = i + 1;
  }
  if (dv.flags1 == -1) {
    dv.flags1 = *(uint *)((int)c_common::vrgtok + itok * 0x1d + 0x15);
    if (499 < (uint)dv.flags1 >> 7) {
      dv.flags1 = dv.flags1 & 0x7fU | 0xf980;
      lVar8 = CONCAT22(uVar12,uVar1);
    }
  }
  else {
    pSVar7 = BATTLE::LpshdefFromTok
                       ((TOK *)CONCAT22(c_common::vrgtok._2_2_,(int)c_common::vrgtok + itok * 0x1d))
    ;
    uVar1 = *(undefined2 *)((int)pSVar7 + 0x38);
    iVar4 = *(int *)((int)c_common::vrgtok + itok * 0x1d + 0x13) - cshKill;
    lVar8 = PUBLIC::__aFulmul(uVar1,0,iVar4,iVar4 >> 0xf);
    uVar13 = 100;
    uVar9 = PUBLIC::__aFulmul(iVar4,iVar4 >> 0xf,dv.flags1 & 0x7f,0);
    cshT = PUBLIC::__aFldiv(uVar9,uVar13);
    if (cshT < 1) {
      cshT = 1;
    }
    uVar13 = 0x32;
    iVar4 = cshT >> 0xf;
    uVar5 = 0;
    uVar12 = 10;
    uVar9 = PUBLIC::__aFulmul(uVar1,0,(uint)dv.flags1 >> 7,0);
    uVar9 = PUBLIC::__aFldiv(uVar9,uVar12,uVar5);
    uVar9 = PUBLIC::__aFulmul(uVar9,cshT,iVar4);
    lVar10 = PUBLIC::__aFldiv(uVar9,uVar13);
    lVar8 = lVar8 - lVar10;
  }
  cshT = *(int *)((int)c_common::vrgtok + itok * 0x1d + 0x13) - cshKill;
  if (cshT < 1) {
    cshT = 0;
    lVar8 = 0;
    uVar11 = PUBLIC::__aFulmul(*(undefined2 *)((int)c_common::vrgtok + itok * 0x1d + 0x11),0,
                               *(undefined2 *)((int)c_common::vrgtok + itok * 0x1d + 0x13),0);
  }
  dpShields._2_2_ = (int)((ulong)uVar11 >> 0x10);
  dpShields._0_2_ = (uint)uVar11;
  dpArmor._2_2_ = (undefined2)((ulong)lVar8 >> 0x10);
  dpArmor._0_2_ = (undefined2)lVar8;
  if (pdv != (DV *)0x0) {
    pdv->flags1 = dv.flags1;
  }
  if (pcsh != (short *)0x0) {
    *pcsh = cshT;
  }
  if (pdpArmor != (long *)0x0) {
    *(undefined2 *)pdpArmor = (undefined2)dpArmor;
    *(undefined2 *)((int)pdpArmor + 2) = dpArmor._2_2_;
  }
  if (pdpShields != (long *)0x0) {
    *(uint *)pdpShields = (uint)dpShields;
    *(undefined2 *)((int)pdpShields + 2) = dpShields._2_2_;
  }
  return;
}



// ======================================================================
// Function: FDamageTok
// Address: 10f0:81d4
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10f08849) */
/* WARNING: Removing unreachable block (ram,0x10f0827b) */
/* WARNING: Removing unreachable block (ram,0x10f087c1) */
/* WARNING: Removing unreachable block (ram,0x10f08ab8) */
/* WARNING: Could not reconcile some variable overlaps */

short __cdecl16far
BATTLE::FDamageTok(TOK *ptok,short itok,long *pdpBeam,long dpTorp,ushort grfWeapon,
                  short fShieldsOnly,long *pcTorp)

{
  byte *pbVar1;
  uint *puVar2;
  long lVar3;
  ulong uVar4;
  int iVar5;
  ushort uVar6;
  uint ishdef_00;
  short sVar7;
  uint uVar8;
  int iVar9;
  uint *puVar10;
  uint uVar11;
  int iVar12;
  int iVar13;
  undefined2 uVar14;
  bool bVar15;
  SHDEF *pSVar16;
  PLANET *lppl_00;
  FLEET *lpfl_00;
  undefined4 uVar17;
  long lVar18;
  long lVar19;
  undefined2 uVar20;
  undefined2 uVar22;
  undefined2 uVar23;
  ulong uVar21;
  ushort pctDpNew;
  long dp;
  short ishdef;
  short pctDp;
  long dpT;
  short csh;
  long cKillMax;
  FLEET *lpfl;
  short cshOrig;
  short i;
  PLANET *lppl;
  long dpOrig;
  long ddpOrig;
  long dpShdef;
  short cshOrigDamaged;
  ushort *pwLosses;
  DV dv;
  short pctSh;
  
  dp._0_2_ = *(uint *)pdpBeam;
  dp._2_2_ = *(int *)((int)pdpBeam + 2);
  PUBLIC::__fmemset(_DATA::lpbBattleCur,0,8);
  *_DATA::lpbBattleCur = (byte)itok;
  *(undefined *)((int)_DATA::lpbBattleCur + 1) = (char)grfWeapon;
  uVar14 = (undefined2)((ulong)ptok >> 0x10);
  iVar12 = (int)ptok;
  if (*(int *)(iVar12 + 0x11) == 0) {
    if (fShieldsOnly != 0) {
      return 0;
    }
  }
  else {
    iVar13 = *(int *)(iVar12 + 0x11);
    iVar9 = *(int *)(iVar12 + 0x11);
    lVar18 = PUBLIC::__aFulmul(iVar13,0,*(undefined2 *)(iVar12 + 0x13),0);
    if (CONCAT22(dp._2_2_,(uint)dp) < lVar18) {
      uVar6 = UTIL::WPackLong(CONCAT22(dp._2_2_,(uint)dp));
      *(ushort *)((int)_DATA::lpbBattleCur + 4) = uVar6;
      iVar5 = PUBLIC::__aFldiv(lVar18 - CONCAT22(dp._2_2_,(uint)dp),*(undefined2 *)(iVar12 + 0x13),0
                              );
      *(int *)(iVar12 + 0x11) = iVar5 + (iVar9 - iVar13);
      dp._0_2_ = 0;
      dp._2_2_ = 0;
    }
    else {
      bVar15 = (uint)dp < (uint)lVar18;
      dp._0_2_ = (uint)dp - (uint)lVar18;
      dp._2_2_ = (dp._2_2_ - (int)((ulong)lVar18 >> 0x10)) - (uint)bVar15;
      uVar6 = UTIL::WPackLong(lVar18);
      *(ushort *)((int)_DATA::lpbBattleCur + 4) = uVar6;
      *(undefined2 *)(iVar12 + 0x11) = 0;
    }
  }
  if (((((uint)dp == 0) && (dp._2_2_ == 0)) || (fShieldsOnly != 0)) && (dpTorp == 0)) {
    *(undefined2 *)((int)_DATA::lpbBattleCur + 6) = *(undefined2 *)(iVar12 + 0x15);
    *(uint *)pdpBeam = (uint)dp;
    *(int *)((int)pdpBeam + 2) = dp._2_2_;
    uVar14 = (undefined2)((ulong)_DATA::lpbBattleCur >> 0x10);
    if ((*(byte *)((int)_DATA::lpbBattleCur + 1) & 4) != 0) {
      pbVar1 = (byte *)((int)_DATA::lpbBattleCur + 1);
      *pbVar1 = *pbVar1 | 0xc0;
    }
    _DATA::lpbBattleCur = (byte *)CONCAT22(_DATA::lpbBattleCur._2_2_,(int)_DATA::lpbBattleCur + 8);
  }
  else {
    if (pcTorp == (long *)0x0) {
      cKillMax._0_2_ = -1;
      cKillMax._2_2_ = 0x7fff;
    }
    else {
      cKillMax._0_2_ = *(int *)pcTorp;
      cKillMax._2_2_ = *(int *)((int)pcTorp + 2);
    }
    lVar18 = dpTorp + CONCAT22(dp._2_2_,(uint)dp);
    ishdef_00 = (uint)*(byte *)(iVar12 + 4);
    pSVar16 = LpshdefFromTok(ptok);
    uVar11 = *(uint *)((int)pSVar16 + 0x38);
    uVar4 = (ulong)uVar11;
    uVar8 = *(uint *)(iVar12 + 0x15);
    if (*(char *)(iVar12 + 3) == '\x01') {
      lppl_00 = UTIL::LpplFromId(ptok->id);
      uVar20 = (undefined2)((ulong)lppl_00 >> 0x10);
      iVar13 = (int)lppl_00;
      if (uVar8 >> 7 != 0) {
        uVar22 = 0;
        uVar23 = 500;
        uVar17 = PUBLIC::__aFulmul();
        lVar19 = PUBLIC::__aFldiv(uVar17,uVar23,uVar22);
        lVar18 = lVar18 + lVar19;
      }
      dp._0_2_ = (uint)lVar18;
      if ((lVar18 < 0) || ((lVar18 < 0x10000 && ((uint)dp < uVar11)))) {
        uVar23 = 0;
        uVar8 = uVar11;
        uVar17 = PUBLIC::__aFulmul();
        uVar8 = PUBLIC::__aFldiv(uVar17,uVar8,uVar23);
        if (*(uint *)(iVar13 + 0x2c) >> 4 == uVar8) {
          iVar9 = *(int *)(iVar13 + 0x2c);
          puVar2 = (uint *)(iVar13 + 0x2c);
          *puVar2 = *puVar2 & 0xf;
          puVar2 = (uint *)(iVar13 + 0x2c);
          *puVar2 = *puVar2 | iVar9 + 0x10U & 0xfff0;
        }
        else {
          uVar23 = 0;
          uVar17 = PUBLIC::__aFulmul();
          iVar9 = PUBLIC::__aFldiv(uVar17,uVar11,uVar23);
          *(uint *)(iVar13 + 0x2c) = *(uint *)(iVar13 + 0x2c) & 0xf | iVar9 << 4;
        }
        uVar23 = (undefined2)((ulong)_DATA::lpbBattleCur >> 0x10);
        *(uint *)((int)_DATA::lpbBattleCur + 6) =
             *(uint *)((int)_DATA::lpbBattleCur + 6) & 0x7f | (*(uint *)(iVar13 + 0x2c) >> 4) << 7;
        _DATA::fStarbaseDamaged = 1;
      }
      else {
        uVar23 = (undefined2)((ulong)_DATA::lpbBattleCur >> 0x10);
        *(uint *)((int)_DATA::lpbBattleCur + 6) =
             *(uint *)((int)_DATA::lpbBattleCur + 6) & 0x7f | 64000;
        *(undefined2 *)((int)_DATA::lpbBattleCur + 2) = 1;
        *(uint *)(iVar12 + 0x1b) = *(uint *)(iVar12 + 0x1b) & 0xfffe;
        *(undefined2 *)(iVar12 + 0x13) = 0;
        _DATA::fStarbaseDied = 1;
        sVar7 = RACE::GetRaceStat((PLAYER *)((int)&c_common::rgplr + *(int *)(iVar13 + 2) * 0xc0),
                                  0xe);
        if (sVar7 != 8) {
          *(uint *)(iVar13 + 4) = *(uint *)(iVar13 + 4) & 0xfdff;
          BUILD::KillQueuedShips(lppl_00);
          BUILD::KillQueuedMassPackets(lppl_00);
        }
      }
      uVar20 = (undefined2)((ulong)_DATA::lpbBattleCur >> 0x10);
      iVar13 = (int)_DATA::lpbBattleCur;
      if (*(uint *)(iVar13 + 6) >> 7 != 0) {
        *(uint *)(iVar13 + 6) = *(uint *)(iVar13 + 6) & 0xff80 | 100;
        *(undefined2 *)(iVar12 + 0x15) = *(undefined2 *)((int)_DATA::lpbBattleCur + 6);
      }
      *(undefined2 *)pdpBeam = 0;
      *(undefined2 *)((int)pdpBeam + 2) = 0;
      _DATA::lpbBattleCur = (byte *)CONCAT22(_DATA::lpbBattleCur._2_2_,(int)_DATA::lpbBattleCur + 8)
      ;
    }
    else {
      if ((*(uint *)(iVar12 + 0x17) >> 8 & 0xf) == 1) {
        *(uint *)(iVar12 + 0x17) = *(uint *)(iVar12 + 0x17) & 0xf0ff;
        *(uint *)(iVar12 + 0x1b) = *(uint *)(iVar12 + 0x1b) & 0xfc1f | 0xe0;
      }
      lpfl_00 = UTIL::LpflFromId(ptok->id);
      iVar13 = *(int *)(iVar12 + 0x13);
      if (uVar8 >> 7 == 0) {
        cshOrigDamaged = 0;
        lVar19 = 0;
      }
      else {
        uVar23 = 0;
        uVar20 = 100;
        uVar17 = PUBLIC::__aFulmul();
        cshOrigDamaged = PUBLIC::__aFldiv(uVar17,uVar20,uVar23);
        if (cshOrigDamaged == 0) {
          cshOrigDamaged = 1;
        }
        uVar23 = 0;
        uVar20 = 500;
        uVar17 = PUBLIC::__aFulmul();
        lVar19 = PUBLIC::__aFldiv(uVar17,uVar20,uVar23);
        if (lVar19 == 0) {
          lVar19 = 1;
        }
      }
      sVar7 = cshOrigDamaged;
      ddpOrig._2_2_ = (int)((ulong)lVar19 >> 0x10);
      ddpOrig._0_2_ = (uint)lVar19;
      puVar10 = (uint *)(c_common::vrgPlrLosses +
                        ((uint)*(byte *)(iVar12 + 2) * 0x10 + ishdef_00) * 2);
      puVar2 = puVar10;
      *puVar2 = *puVar2 | 0x8000;
      csh = iVar13;
      if (cshOrigDamaged != 0) {
        csh = cshOrigDamaged;
        lVar3 = CONCAT22(-(uint)(uVar11 < (uint)ddpOrig) - ddpOrig._2_2_,uVar11 - (uint)ddpOrig);
        while (((lVar3 <= lVar18 && (csh != 0)) && (((int)cKillMax != 0 || (cKillMax._2_2_ != 0)))))
        {
          lVar18 = lVar18 - lVar3;
          csh = csh + -1;
          bVar15 = (int)cKillMax == 0;
          cKillMax._0_2_ = (int)cKillMax + -1;
          cKillMax._2_2_ = cKillMax._2_2_ - (uint)bVar15;
          if ((*puVar10 & 0x1fff) < 0x1fff) {
            puVar2 = puVar10;
            *puVar2 = *puVar2 + 1;
          }
        }
        uVar4 = lVar19 + lVar3;
        cshOrigDamaged = csh;
        csh = csh + (iVar13 - sVar7);
      }
      while ((((long)uVar4 <= lVar18 && (csh != 0)) &&
             (((int)cKillMax != 0 || (cKillMax._2_2_ != 0))))) {
        lVar18 = lVar18 - uVar4;
        csh = csh + -1;
        bVar15 = (int)cKillMax == 0;
        cKillMax._0_2_ = (int)cKillMax + -1;
        cKillMax._2_2_ = cKillMax._2_2_ - (uint)bVar15;
        if ((*puVar10 & 0x1fff) < 0x1fff) {
          puVar2 = puVar10;
          *puVar2 = *puVar2 + 1;
        }
      }
      if ((cKillMax._2_2_ < 1) && ((cKillMax._2_2_ < 0 || ((int)cKillMax == 0)))) {
        lVar18 = 0;
      }
      iVar13 = csh >> 0xf;
      if ((lVar18 == 0) || (csh == 0)) {
        if (cshOrigDamaged == 0) {
          pctSh = 0;
          pctDp = 0;
        }
        else {
          sVar7 = csh;
          lVar19 = PUBLIC::__aFulmul();
          pctSh = PUBLIC::__aFldiv(lVar19 + csh + -1,sVar7,iVar13);
          pctDp = *(uint *)(iVar12 + 0x15) >> 7;
        }
      }
      else {
        if (cshOrigDamaged != 0) {
          lVar19 = PUBLIC::__aFulmul(lVar19,cshOrigDamaged,cshOrigDamaged >> 0xf);
          lVar18 = lVar18 + lVar19 + csh + -1;
        }
        lVar18 = PUBLIC::__aFldiv(lVar18,csh,iVar13);
        if (lVar18 == 0) {
          lVar18 = 1;
        }
        uVar21 = uVar4;
        lVar19 = PUBLIC::__aFulmul();
        pctDp = PUBLIC::__aFldiv(lVar19 + uVar4 + -1,uVar21);
        if (pctDp == 0) {
          pctDp = 1;
        }
        pctSh = 100;
      }
      lpfl._2_2_ = (undefined2)((ulong)lpfl_00 >> 0x10);
      lpfl._0_2_ = (int)lpfl_00;
      *(int *)((int)_DATA::lpbBattleCur + 2) = *(int *)(iVar12 + 0x13) - csh;
      if (csh != *(int *)(iVar12 + 0x13)) {
        KillShips(ptok,*(short *)((int)_DATA::lpbBattleCur + 2),ishdef_00,lpfl_00,1);
      }
      if (csh != 0) {
        if (499 < pctDp) {
          pctDp = 499;
        }
        uVar11 = pctDp << 7 | pctSh & 0x7fU;
        *(uint *)(iVar12 + 0x15) = uVar11;
        *(uint *)((int)lpfl + 0x2c + ishdef_00 * 2) = uVar11;
        lVar18 = 0;
      }
      if (dpTorp < lVar18) {
        *(int *)pdpBeam = (int)(lVar18 - dpTorp);
        *(undefined2 *)((int)pdpBeam + 2) = (int)((ulong)(lVar18 - dpTorp) >> 0x10);
      }
      else {
        *(undefined2 *)pdpBeam = 0;
        *(undefined2 *)((int)pdpBeam + 2) = 0;
      }
      *(undefined2 *)((int)_DATA::lpbBattleCur + 6) = *(undefined2 *)(iVar12 + 0x15);
      _DATA::lpbBattleCur = (byte *)CONCAT22(_DATA::lpbBattleCur._2_2_,(int)_DATA::lpbBattleCur + 8)
      ;
      if (pcTorp != (long *)0x0) {
        *(int *)pcTorp = (int)cKillMax;
        *(int *)((int)pcTorp + 2) = cKillMax._2_2_;
      }
    }
  }
  return 1;
}



// ======================================================================
// Function: FAttack
// Address: 10f0:69ac
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10f0798c) */
/* WARNING: Removing unreachable block (ram,0x10f07315) */
/* WARNING: Removing unreachable block (ram,0x10f070f6) */
/* WARNING: Removing unreachable block (ram,0x10f074c6) */
/* WARNING: Removing unreachable block (ram,0x10f072a4) */
/* WARNING: Removing unreachable block (ram,0x10f06f66) */
/* WARNING: Removing unreachable block (ram,0x10f0707c) */
/* WARNING: Removing unreachable block (ram,0x10f07265) */
/* WARNING: Removing unreachable block (ram,0x10f07463) */
/* WARNING: Removing unreachable block (ram,0x10f0781f) */
/* WARNING: Removing unreachable block (ram,0x10f07733) */
/* WARNING: Removing unreachable block (ram,0x10f079ee) */
/* WARNING: Removing unreachable block (ram,0x10f0751f) */
/* WARNING: Removing unreachable block (ram,0x10f07498) */
/* WARNING: Removing unreachable block (ram,0x10f07183) */
/* WARNING: Removing unreachable block (ram,0x10f079c8) */
/* WARNING: Removing unreachable block (ram,0x10f07b2d) */
/* WARNING: Removing unreachable block (ram,0x10f0774a) */
/* WARNING: Removing unreachable block (ram,0x10f07b4d) */
/* WARNING: Removing unreachable block (ram,0x10f077de) */
/* WARNING: Removing unreachable block (ram,0x10f07b89) */
/* WARNING: Removing unreachable block (ram,0x10f07c92) */
/* WARNING: Removing unreachable block (ram,0x10f07ca9) */
/* WARNING: Could not reconcile some variable overlaps */

short __cdecl16far BATTLE::FAttack(short itokAttacker,short init,BTLREC *lpbtlrec,ushort grfAttack)

{
  short sVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  short *psVar7;
  undefined2 uVar8;
  undefined2 uVar9;
  undefined2 uVar10;
  long lVar11;
  long lVar12;
  undefined4 uVar13;
  long lVar14;
  long lVar15;
  undefined2 uVar16;
  undefined2 uVar17;
  undefined2 uVar18;
  undefined uVar19;
  undefined uVar20;
  long ntk;
  long dpHitArmor;
  long dpShieldCur;
  PART part;
  TOK *ptokE;
  long dpCol;
  short itok;
  long dp;
  short fPrimary;
  long cTorpHit;
  HUL *lphul;
  long dpT;
  long lValue;
  SHDEF *lpshdef;
  TOK *ptokTarget;
  long pctHit;
  short cItem;
  ushort grfWeapon;
  long cTorpBase;
  short i;
  long cTorpsLeft;
  long cTorpFire;
  long cTorpMiss;
  short ihs;
  short dxRangeCur;
  short fSetItok;
  long score;
  long dpMain;
  short itokTarget;
  short ctokDamaged;
  TOK *ptok;
  long scoreBest;
  long dpSingle;
  long dpArmorLeft;
  SHDEF *lpshdefE;
  short dz;
  long dpShieldLeft;
  
  dxRangeCur = 0;
  fSetItok = 0;
  ctokDamaged = 0;
  iVar3 = (int)c_common::vrgtok + itokAttacker * 0x1d;
  ptok = (TOK *)CONCAT22(c_common::vrgtok._2_2_,iVar3);
  lphul = (HUL *)LpshdefFromTok((TOK *)CONCAT13((char)((uint)c_common::vrgtok._2_2_ >> 8),
                                                CONCAT12((char)c_common::vrgtok._2_2_,iVar3)));
  lVar15 = CONCAT22(dpMain._2_2_,(undefined2)dpMain);
  lVar11 = CONCAT22(cTorpsLeft._2_2_,(undefined2)cTorpsLeft);
  lVar14 = CONCAT22(dp._2_2_,(int)dp);
  ihs = 0;
  lpshdef = (SHDEF *)lphul;
  do {
    uVar8 = (undefined2)((ulong)lphul >> 0x10);
    iVar3 = (int)lphul;
    iVar6 = (int)lpbtlrec;
    uVar9 = (undefined2)((ulong)lpbtlrec >> 0x10);
    if ((int)(uint)*(byte *)(iVar3 + 0x7a) <= ihs) {
      *(short *)(iVar6 + 2) = ctokDamaged;
      return (uint)(ctokDamaged != 0);
    }
    if (((*(uint *)(iVar3 + 0x3a + ihs * 4) & 0x30) != 0) &&
       (*(uint *)(iVar3 + ihs * 4 + 0x3c) >> 8 != 0)) {
      psVar7 = (short *)(iVar3 + 0x3a + ihs * 4);
      part.hs.grhst = *psVar7;
      part.hs.flags2 = psVar7[1];
      _DATA::idPlayer = (int)*(byte *)((int)ptok + 2);
      dp = lVar14;
      cTorpsLeft = lVar11;
      dpMain = lVar15;
      PARTS::FLookupPart(&part);
      _DATA::idPlayer = -1;
      cItem = *(uint *)((int)lphul + ihs * 4 + 0x3c) >> 8;
      uVar8 = (undefined2)((ulong)ptok >> 0x10);
      uVar10 = (undefined2)((ulong)part.pterra >> 0x10);
      iVar3 = (int)part.pterra;
      i = (uint)*(byte *)((int)ptok + 6) + *(int *)(iVar3 + 0x38);
      if (0x3f < i) {
        i = 0x3f;
      }
      lVar14 = dp;
      lVar11 = cTorpsLeft;
      lVar15 = dpMain;
      if (i == init) {
        dxRangeCur = (uint)(*(char *)((int)ptok + 3) == '\x01') + *(int *)(iVar3 + 0x34);
        if ((part.hs.grhst == 0x10) && ((*(uint *)(iVar3 + 0x3a) & 2) != 0)) {
          iVar3 = *(int *)(iVar3 + 0x36);
          PUBLIC::__aFulmul(iVar3,iVar3 >> 0xf,cItem,0);
          lVar14 = PUBLIC::__aFulmul();
          if (*(int *)((int)part.pterra + 0x36) < 200) {
            grfWeapon = 1;
          }
          else {
            grfWeapon = 2;
          }
          uVar8 = (undefined2)((ulong)ptok >> 0x10);
          if (*(char *)((int)ptok + 0xd) != '\0') {
            dp = lVar14;
            PUBLIC::__aFulmul(lVar14,*(undefined *)((int)ptok + 0xd),0);
            lVar14 = PUBLIC::__aFldiv();
          }
          ptokE = (TOK *)CONCAT22(c_common::vrgtok._2_2_,(int)c_common::vrgtok);
          dpT = lVar14;
          lVar11 = cTorpsLeft;
          lVar15 = dpMain;
          for (itok = 0; itok < c_common::vctok; itok = itok + 1) {
            uVar8 = (undefined2)((ulong)ptokE >> 0x10);
            iVar3 = (int)ptokE;
            if ((*(uint *)(iVar3 + 0x1b) & 1) != 0) {
              uVar10 = (undefined2)((ulong)ptok >> 0x10);
              if ((*(char *)(iVar3 + 2) != *(char *)((int)ptok + 2)) &&
                 ((1 << (*(byte *)(iVar3 + 2) & 0x1f) & grfAttack) != 0)) {
                dp = lVar14;
                cTorpsLeft = lVar11;
                dpMain = lVar15;
                sVar1 = DzFromBrcBrc(*(byte *)(iVar3 + 5),*(byte *)((int)ptok + 5));
                lVar14 = dp;
                lVar11 = cTorpsLeft;
                lVar15 = dpMain;
                if (sVar1 <= dxRangeCur) {
                  sVar1 = FIsTargetOfMdTarget(ptokE,*(uint *)((int)ptok + 0x17) & 0xf);
                  lVar14 = dp;
                  if (sVar1 == 0) {
                    sVar1 = FIsTargetOfMdTarget(ptokE,*(uint *)((int)ptok + 0x17) >> 4 & 0xf);
                    lVar14 = dp;
                    lVar11 = cTorpsLeft;
                    lVar15 = dpMain;
                    if (sVar1 == 0) goto LAB_10f0_6bfa;
                  }
                  if (*(byte *)(iVar3 + 0xe) < 100) {
                    dp = lVar14;
                    PUBLIC::__aFulmul(lVar14,*(undefined *)(iVar3 + 0xe),0);
                    lVar14 = PUBLIC::__aFldiv();
                  }
                  dp = lVar14;
                  sVar1 = FDamageTok(ptokE,itok,&dp,0,grfWeapon,
                                     *(uint *)((int)part.pterra + 0x3a) & 1,(long *)0x0);
                  lVar14 = dpT;
                  lVar11 = cTorpsLeft;
                  lVar15 = dpMain;
                  if (sVar1 != 0) {
                    if (fSetItok == 0) {
                      fSetItok = 1;
                      *(uint *)(iVar6 + 4) = *(uint *)(iVar6 + 4) & 0xff | itok << 8;
                    }
                    ctokDamaged = ctokDamaged + 1;
                  }
                }
              }
            }
LAB_10f0_6bfa:
            ptokE = (TOK *)CONCAT22(uVar8,iVar3 + 0x1d);
          }
        }
        else {
          if (part.hs.grhst == 0x10) {
            iVar3 = *(int *)(iVar3 + 0x36);
            PUBLIC::__aFulmul(iVar3,iVar3 >> 0xf,cItem,0);
            lVar15 = PUBLIC::__aFulmul();
            lVar11 = 0;
            lVar12 = score;
          }
          else {
            dpMain._0_2_ = 0;
            dpMain._2_2_ = 0;
            lVar11 = PUBLIC::__aFulmul();
            lVar15 = CONCAT22(dpMain._2_2_,(undefined2)dpMain);
            lVar12 = score;
          }
          do {
            for (fPrimary = 1; -1 < fPrimary; fPrimary = fPrimary + -1) {
              scoreBest = 0;
              ptokTarget = (TOK *)0x0;
              ptokE = (TOK *)CONCAT22(c_common::vrgtok._2_2_,(int)c_common::vrgtok);
              for (itok = 0; itok < c_common::vctok; itok = itok + 1) {
                uVar8 = (undefined2)((ulong)ptokE >> 0x10);
                iVar3 = (int)ptokE;
                if ((*(uint *)(iVar3 + 0x1b) & 1) != 0) {
                  uVar10 = (undefined2)((ulong)ptok >> 0x10);
                  if ((*(char *)(iVar3 + 2) != *(char *)((int)ptok + 2)) &&
                     ((1 << (*(byte *)(iVar3 + 2) & 0x1f) & grfAttack) != 0)) {
                    score = lVar12;
                    cTorpsLeft = lVar11;
                    dpMain = lVar15;
                    sVar1 = DzFromBrcBrc(*(byte *)(iVar3 + 5),*(byte *)((int)ptok + 5));
                    lVar12 = score;
                    lVar11 = cTorpsLeft;
                    lVar15 = dpMain;
                    if (sVar1 <= dxRangeCur) {
                      uVar10 = (undefined2)((ulong)ptok >> 0x10);
                      if (fPrimary == 0) {
                        uVar2 = *(uint *)((int)ptok + 0x17) >> 4;
                      }
                      else {
                        uVar2 = *(uint *)((int)ptok + 0x17);
                      }
                      sVar1 = FIsTargetOfMdTarget(ptokE,uVar2 & 0xf);
                      lVar12 = score;
                      lVar11 = cTorpsLeft;
                      lVar15 = dpMain;
                      if (sVar1 != 0) {
                        lpshdefE = LpshdefFromTok(ptokE);
                        lVar14 = PUBLIC::__aFulmul();
                        if (lVar14 < 100000) {
                          lValue = lVar14;
                          lVar14 = PUBLIC::__aFulmul();
                        }
                        else {
                          lVar14 = 10000000;
                        }
                        dpSingle._0_2_ = *(undefined2 *)((int)lpshdefE + 0x38);
                        dpSingle._2_2_ = 0;
                        lValue = lVar14;
                        lVar14 = PUBLIC::__aFulmul();
                        dpShieldLeft = lVar14;
                        lVar14 = PUBLIC::__aFulmul();
                        if (*(int *)(iVar3 + 0x15) != 0) {
                          uVar10 = *(undefined2 *)(iVar3 + 0x13);
                          uVar18 = 0;
                          uVar2 = *(uint *)(iVar3 + 0x15) & 0x7f;
                          uVar17 = 0;
                          uVar16 = 10;
                          dpArmorLeft = lVar14;
                          uVar13 = PUBLIC::__aFulmul((undefined2)dpSingle,dpSingle._2_2_,
                                                     *(uint *)(iVar3 + 0x15) >> 7,0);
                          uVar13 = PUBLIC::__aFldiv(uVar13,uVar16);
                          PUBLIC::__aFulmul(uVar13,uVar2,uVar17);
                          uVar13 = PUBLIC::__aFldiv();
                          PUBLIC::__aFulmul(uVar13,uVar10,uVar18);
                          lVar14 = PUBLIC::__aFldiv();
                          lVar14 = dpArmorLeft - lVar14;
                        }
                        if (lVar14 < 1) {
                          lVar14 = 1;
                        }
                        dpArmorLeft = lVar14;
                        if ((part.hs.grhst == 0x10) || (part.hs.grhst != 0x20)) {
                          if (*(byte *)(iVar3 + 0xe) < 100) {
                            PUBLIC::__aFulmul(lValue,*(undefined *)(iVar3 + 0xe),0);
                            lVar14 = PUBLIC::__aFldiv();
                            lValue = lVar14;
                          }
                          if ((*(uint *)((int)part.pterra + 0x3a) & 1) == 0) {
                            PUBLIC::__aFulmul(lValue,100,0);
                            lVar12 = PUBLIC::__aFldiv();
                            if (lVar12 < 1) {
                              lVar12 = 1;
                            }
                          }
                          else if (dpShieldLeft < 1) {
                            lVar12 = 0;
                          }
                          else {
                            PUBLIC::__aFulmul(lValue,100,0);
                            lVar12 = PUBLIC::__aFldiv();
                          }
                        }
                        else {
                          pctHit._0_2_ = *(uint *)((int)part.pterra + 0x3a);
                          pctHit._2_2_ = (int)(uint)pctHit >> 0xf;
                          uVar10 = (undefined2)((ulong)ptok >> 0x10);
                          iVar5 = (int)ptok;
                          if (*(byte *)(iVar5 + 0xc) < *(byte *)(iVar3 + 0xb)) {
                            iVar5 = (uint)*(byte *)(iVar3 + 0xb) - (uint)*(byte *)(iVar5 + 0xc);
                            PUBLIC::__aFulmul((uint)pctHit,pctHit._2_2_,iVar5,iVar5 >> 0xf);
                            uVar13 = PUBLIC::__aFldiv();
                            pctHit = CONCAT22((pctHit._2_2_ - (int)((ulong)uVar13 >> 0x10)) -
                                              (uint)((uint)pctHit < (uint)uVar13),
                                              (uint)pctHit - (uint)uVar13);
                          }
                          else {
                            iVar5 = (uint)*(byte *)(iVar5 + 0xc) - (uint)*(byte *)(iVar3 + 0xb);
                            PUBLIC::__aFulmul(100 - (uint)pctHit,
                                              -(uint)(100 < (uint)pctHit) - pctHit._2_2_,iVar5,
                                              iVar5 >> 0xf);
                            lVar14 = PUBLIC::__aFldiv();
                            pctHit = lVar14 + CONCAT22(pctHit._2_2_,(uint)pctHit);
                          }
                          if (pctHit < 1) {
                            lVar12 = 0;
                          }
                          else {
                            if (dpArmorLeft < 100000) {
                              uVar20 = (undefined)((ulong)pctHit >> 0x10);
                              uVar19 = (undefined)pctHit;
                              PUBLIC::__aFulmul(dpArmorLeft,100,0);
                              PUBLIC::__aFlshl(uVar19,uVar20);
                              lVar15 = PUBLIC::__aFldiv();
                              lVar14 = pctHit;
                            }
                            else {
                              PUBLIC::__aFldiv(dpArmorLeft,pctHit);
                              lVar15 = PUBLIC::__aFulmul();
                              lVar14 = pctHit;
                            }
                            pctHit._2_2_ = (int)((ulong)lVar14 >> 0x10);
                            pctHit._0_2_ = (uint)lVar14;
                            pctHit = lVar14;
                            if (dpShieldLeft < 100000) {
                              PUBLIC::__aFldiv();
                              PUBLIC::__aFldiv();
                              PUBLIC::__aFulmul(dpShieldLeft,100,0);
                              lVar14 = PUBLIC::__aFldiv();
                            }
                            else {
                              iVar5 = 100 - (uint)pctHit;
                              iVar4 = -(uint)(100 < (uint)pctHit) - pctHit._2_2_;
                              lVar14 = PUBLIC::__aFldiv(iVar5,iVar4,8,0);
                              lVar11 = PUBLIC::__aFldiv(pctHit,2,0);
                              PUBLIC::__aFldiv(dpShieldLeft,lVar14 + lVar11);
                              lVar14 = PUBLIC::__aFulmul();
                            }
                            PUBLIC::__aFulmul();
                            uVar16 = 0;
                            uVar10 = 100;
                            PUBLIC::__aFulmul(lVar14,pctHit);
                            lVar11 = PUBLIC::__aFldiv();
                            PUBLIC::__aFulmul(dpArmorLeft - lVar11,uVar10,uVar16);
                            lVar11 = PUBLIC::__aFldiv();
                            if (lVar14 + lVar11 <= lVar15) {
                              lVar15 = lVar11 + lVar14;
                            }
                            if (lVar15 < 1) {
                              lVar12 = 0;
                            }
                            else {
                              score = lVar15;
                              lVar12 = PUBLIC::__aFldiv();
                              if (lVar12 < 1) {
                                lVar12 = 1;
                              }
                            }
                          }
                        }
                        lVar11 = cTorpsLeft;
                        lVar15 = dpMain;
                        if (scoreBest < lVar12) {
                          ptokTarget = ptokE;
                          itokTarget = itok;
                          scoreBest = lVar12;
                        }
                      }
                    }
                  }
                }
                ptokE = (TOK *)CONCAT22(uVar8,iVar3 + 0x1d);
              }
              if (((int)ptokTarget != 0) || (ptokTarget._2_2_ != 0)) break;
            }
            score = lVar12;
            if (((int)ptokTarget == 0) && (lVar14 = dp, ptokTarget._2_2_ == 0)) break;
            cTorpsLeft = lVar11;
            dpMain = lVar15;
            dz = DzFromBrcBrc(*(byte *)((int)ptokTarget + 5),*(byte *)((int)ptok + 5));
            iVar3 = (int)ptok;
            uVar8 = (undefined2)((ulong)ptok >> 0x10);
            if (part.hs.grhst == 0x10) {
              dp = dpMain;
              if (*(char *)(iVar3 + 0xd) != '\0') {
                PUBLIC::__aFulmul(dpMain,*(undefined *)(iVar3 + 0xd),0);
                lVar14 = PUBLIC::__aFldiv();
                dp = lVar14;
              }
              uVar8 = (undefined2)((ulong)ptokTarget >> 0x10);
              if (*(byte *)((int)ptokTarget + 0xe) < 100) {
                PUBLIC::__aFulmul(dp,*(undefined *)((int)ptokTarget + 0xe),0);
                lVar14 = PUBLIC::__aFldiv();
                dp = lVar14;
              }
              if (0 < dz) {
                uVar8 = (undefined2)((ulong)part.pterra >> 0x10);
                if (0 < *(int *)((int)part.pterra + 0x34)) {
                  iVar3 = *(int *)((int)part.pterra + 0x34);
                  iVar5 = iVar3 >> 0xf;
                  uVar13 = PUBLIC::__aFulmul();
                  uVar13 = PUBLIC::__aFldiv(uVar13,iVar3,iVar5);
                  PUBLIC::__aFulmul(dp,100 - (uint)uVar13,
                                    -(uint)(100 < (uint)uVar13) - (int)((ulong)uVar13 >> 0x10));
                  lVar14 = PUBLIC::__aFldiv();
                  dp = lVar14;
                }
              }
              uVar8 = (undefined2)((ulong)part.pterra >> 0x10);
              if (*(int *)((int)part.pterra + 0x36) < 200) {
                grfWeapon = 1;
              }
              else {
                grfWeapon = 2;
              }
              uVar10 = 0;
              dpT = dp;
              sVar1 = FDamageTok(ptokTarget,itokTarget,&dp,0,grfWeapon,
                                 *(uint *)((int)part.pterra + 0x3a) & 1,(long *)0x0);
              if (sVar1 != 0) {
                if (fSetItok == 0) {
                  *(uint *)(iVar6 + 4) = *(uint *)(iVar6 + 4) & 0xff | itokTarget << 8;
                  fSetItok = 1;
                }
                ctokDamaged = ctokDamaged + 1;
              }
              if ((dp < 1) || (dpT < 1)) {
                lVar15 = 0;
                lVar11 = cTorpsLeft;
              }
              else {
                if ((((dpMain < 0x20000) && (dpMain < 0x10000)) && (dp < 0x20000)) && (dp < 0x10000)
                   ) {
                  PUBLIC::__aFulmul(dpMain,dp);
                  lVar15 = PUBLIC::__aFldiv();
                }
                else {
                  uVar8 = PUBLIC::__ftol();
                  lVar15 = CONCAT22(uVar10,uVar8);
                }
                lVar11 = cTorpsLeft;
                lValue = lVar15;
                if (dpMain + -1 < lVar15) {
                  lVar15 = dpMain + -1;
                }
              }
            }
            else {
              lVar15 = dpMain;
              lVar11 = cTorpsLeft;
              if ((part.hs.grhst == 0x20) && (0 < cTorpsLeft)) {
                grfWeapon = 4;
                uVar10 = cTorpsLeft._2_2_;
                cTorpBase = cTorpsLeft;
                cTorpHit._0_2_ =
                     CTorpHit(cTorpsLeft,(int)ptokTarget,ptokTarget._2_2_,
                              (char)*(undefined2 *)((int)part.pterra + 0x3a),
                              *(undefined *)(iVar3 + 0xc));
                cTorpHit._2_2_ = uVar10;
                lpshdefE = LpshdefFromTok(ptokTarget);
                dpSingle._0_2_ = *(undefined2 *)((int)lpshdefE + 0x38);
                dpSingle._2_2_ = 0;
                lVar14 = PUBLIC::__aFulmul();
                dpShieldLeft = lVar14;
                lVar14 = PUBLIC::__aFulmul();
                uVar8 = (undefined2)((ulong)ptokTarget >> 0x10);
                iVar3 = (int)ptokTarget;
                if (*(int *)(iVar3 + 0x15) != 0) {
                  uVar10 = *(undefined2 *)(iVar3 + 0x13);
                  uVar18 = 0;
                  uVar2 = *(uint *)(iVar3 + 0x15) & 0x7f;
                  uVar17 = 0;
                  uVar16 = 10;
                  dpArmorLeft = lVar14;
                  uVar13 = PUBLIC::__aFulmul((undefined2)dpSingle,dpSingle._2_2_,
                                             *(uint *)(iVar3 + 0x15) >> 7,0);
                  uVar13 = PUBLIC::__aFldiv(uVar13,uVar16);
                  PUBLIC::__aFulmul(uVar13,uVar2,uVar17);
                  uVar13 = PUBLIC::__aFldiv();
                  PUBLIC::__aFulmul(uVar13,uVar10,uVar18);
                  lVar14 = PUBLIC::__aFldiv();
                  lVar14 = dpArmorLeft - lVar14;
                }
                dp._0_2_ = *(int *)((int)part.pterra + 0x36);
                dp._2_2_ = (int)dp >> 0xf;
                if ((7 < (part.hs.flags2 & 0xffU)) && ((part.hs.flags2 & 0xffU) < 0xc)) {
                  if (dpShieldLeft < 1) {
                    dpArmorLeft = lVar14;
                    dp._0_2_ = PUBLIC::__aFlshl();
                    lVar14 = dpArmorLeft;
                  }
                  grfWeapon = grfWeapon | 8;
                }
                i = *(int *)((int)ptokTarget + 0x13);
                dpArmorLeft = lVar14;
                if (i < cTorpBase) {
                  lVar14 = PUBLIC::__aFulmul();
                  if (lVar14 <= dpArmorLeft) goto LAB_10f0_79f6;
                  for (; i <= cTorpBase; i = i + 1) {
                    PUBLIC::__aFulmul(i,i >> 0xf,(undefined2)cTorpHit,cTorpHit._2_2_);
                    lVar14 = PUBLIC::__aFldiv();
                    cTorpMiss._0_2_ = i - (uint)lVar14;
                    cTorpMiss._2_2_ =
                         ((i >> 0xf) - (int)((ulong)lVar14 >> 0x10)) -
                         (uint)((uint)i < (uint)lVar14);
                    cTorpFire = lVar14;
                    PUBLIC::__aFulmul((int)cTorpMiss,cTorpMiss._2_2_,(int)dp,dp._2_2_);
                    lVar14 = PUBLIC::__aFldiv();
                    lVar14 = dpShieldLeft - lVar14;
                    if ((lVar14 < 0x10000) && (lVar14 < 0)) {
                      lVar14 = 0;
                    }
                    dpShieldCur._2_2_ = (int)((ulong)lVar14 >> 0x10);
                    dpShieldCur._0_2_ = (uint)lVar14;
                    PUBLIC::__aFulmul(cTorpFire,(int)dp,dp._2_2_);
                    lVar11 = PUBLIC::__aFldiv();
                    iVar3 = (dpShieldCur._2_2_ - (int)((ulong)lVar11 >> 0x10)) -
                            (uint)((uint)dpShieldCur < (uint)lVar11);
                    PUBLIC::__aFulmul(cTorpFire,(int)dp,dp._2_2_);
                    lVar15 = PUBLIC::__aFldiv();
                    if ((iVar3 < 1) && (iVar3 < 0)) {
                      lVar15 = lVar15 - (lVar14 - lVar11);
                    }
                    if (dpArmorLeft <= lVar15) break;
                  }
                }
                else {
LAB_10f0_79f6:
                  cTorpFire = CONCAT22(cTorpHit._2_2_,(undefined2)cTorpHit);
                  cTorpMiss = cTorpBase - cTorpFire;
                }
                PUBLIC::__aFulmul(cTorpMiss,(int)dp,dp._2_2_);
                lVar14 = PUBLIC::__aFldiv();
                if (0 < lVar14) {
                  dpCol = lVar14;
                  sVar1 = FDamageTok(ptokTarget,itokTarget,&dpCol,0,grfWeapon | 0x80,1,(long *)0x0);
                  lVar14 = dpCol;
                  if (sVar1 != 0) {
                    ctokDamaged = ctokDamaged + 1;
                  }
                }
                dpCol = lVar14;
                PUBLIC::__aFulmul(cTorpFire,(int)dp,dp._2_2_);
                lVar14 = PUBLIC::__aFldiv();
                cTorpBase = cTorpFire + cTorpMiss;
                dpT = lVar14;
                FDamageTok(ptokTarget,itokTarget,&dpT,lVar14,grfWeapon,0,&cTorpBase);
                ctokDamaged = ctokDamaged + 1;
                if (fSetItok == 0) {
                  fSetItok = 1;
                  *(uint *)(iVar6 + 4) = *(uint *)(iVar6 + 4) & 0xff | itokTarget << 8;
                }
                lVar15 = dpMain;
                lVar11 = cTorpsLeft - (cTorpFire + cTorpMiss);
              }
            }
            lVar12 = score;
          } while ((0 < lVar15) || (lVar14 = dp, 0 < lVar11));
        }
      }
    }
    ihs = ihs + 1;
  } while( true );
}



// ======================================================================
// Function: RegenShield
// Address: 10f0:3c16
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10f03c92) */
/* WARNING: Could not reconcile some variable overlaps */

void __cdecl16far BATTLE::RegenShield(TOK *ptok)

{
  uint uVar1;
  undefined2 uVar2;
  undefined2 uVar3;
  int iVar4;
  undefined2 uVar5;
  SHDEF *pSVar6;
  long lVar7;
  long dpOrig;
  long dpNew;
  
  uVar5 = (undefined2)((ulong)ptok >> 0x10);
  iVar4 = (int)ptok;
  uVar1 = (uint)*(byte *)(iVar4 + 2);
  pSVar6 = LpshdefFromTok(ptok);
  uVar3 = (undefined2)((ulong)pSVar6 >> 0x10);
  uVar2 = UTIL::DpShieldOfShdef(pSVar6,uVar1);
  if (*(int *)(iVar4 + 0x11) != 0) {
    lVar7 = PUBLIC::__aFldiv(uVar2,uVar3,10,0);
    lVar7 = lVar7 + (ulong)*(uint *)(iVar4 + 0x11);
    dpNew._0_2_ = (undefined2)lVar7;
    if (CONCAT22(uVar3,uVar2) < lVar7) {
      dpNew._0_2_ = uVar2;
    }
    *(undefined2 *)(iVar4 + 0x11) = (undefined2)dpNew;
  }
  return;
}



// ======================================================================
// Function: CTorpHit
// Address: 10f0:6790
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10f068d2) */
/* WARNING: Removing unreachable block (ram,0x10f068f3) */
/* WARNING: Could not reconcile some variable overlaps */

uint __cdecl16far
BATTLE::CTorpHit(uint cTorpBase,int param_2,undefined4 ptok,uint pctBase,uint pctBC)

{
  short sVar1;
  bool bVar2;
  undefined4 uVar3;
  long lVar4;
  undefined2 uVar5;
  undefined2 uVar6;
  long cTorpHit;
  long pctHit;
  short i;
  long pctJam;
  
  if (((cTorpBase == 0) && (param_2 == 0)) || (pctBase == 0)) {
    cTorpHit._0_2_ = 0;
  }
  else {
    pctJam._0_2_ = (uint)*(byte *)((int)ptok + 0xb);
    pctJam._2_2_ = 0;
    if (((uint)pctJam != 0) && (pctBC != 0)) {
      bVar2 = (uint)pctJam < pctBC;
      pctJam._0_2_ = (uint)pctJam - pctBC;
      pctJam._2_2_ = -(uint)bVar2 - ((int)pctBC >> 0xf);
      if ((pctJam._2_2_ < 1) && (pctJam._2_2_ < 0)) {
        pctBC = -(uint)pctJam;
        pctJam._0_2_ = 0;
        pctJam._2_2_ = 0;
      }
      else {
        pctBC = 0;
      }
    }
    if (pctBC == 0) {
      if (((uint)pctJam == 0) && (pctJam._2_2_ == 0)) {
        lVar4 = (long)(int)pctBase;
      }
      else {
        uVar6 = 0;
        uVar5 = 100;
        uVar3 = PUBLIC::__aFulmul(pctBase,(int)pctBase >> 0xf,100 - (uint)pctJam,
                                  -(uint)(100 < (uint)pctJam) - pctJam._2_2_);
        lVar4 = PUBLIC::__aFldiv(uVar3,uVar5,uVar6);
      }
    }
    else {
      uVar6 = 0;
      uVar5 = 100;
      uVar3 = PUBLIC::__aFulmul(100 - pctBase,-(uint)(100 < pctBase) - ((int)pctBase >> 0xf),
                                100 - pctBC,(int)(100 - pctBC) >> 0xf);
      uVar3 = PUBLIC::__aFldiv(uVar3,uVar5,uVar6);
      lVar4 = CONCAT22(-(uint)(100 < (uint)uVar3) - (int)((ulong)uVar3 >> 0x10),100 - (uint)uVar3);
    }
    if (lVar4 < 1) {
      lVar4 = 1;
    }
    pctHit._0_2_ = (int)lVar4;
    cTorpHit._0_2_ = cTorpBase;
    if (lVar4 < 100) {
      if ((param_2 < 0) || ((param_2 < 1 && (cTorpBase < 0xc9)))) {
        cTorpHit._0_2_ = 0;
        for (i = 0; (i >> 0xf < param_2 || ((i >> 0xf <= param_2 && ((uint)i < cTorpBase))));
            i = i + 1) {
          sVar1 = UTILGEN::Random(100);
          if (sVar1 < (int)pctHit) {
            cTorpHit._0_2_ = (uint)cTorpHit + 1;
          }
        }
      }
      else {
        uVar6 = 0;
        uVar5 = 100;
        uVar3 = PUBLIC::__aFulmul(cTorpBase,param_2,lVar4);
        cTorpHit._0_2_ = PUBLIC::__aFldiv(uVar3,uVar5,uVar6);
      }
    }
  }
  return (uint)cTorpHit;
}



// ======================================================================
// Function: DpFromPtokBrcToBrc
// Address: 10f0:4d2e
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x10f04fe7) */
/* WARNING: Removing unreachable block (ram,0x10f052c0) */
/* WARNING: Removing unreachable block (ram,0x10f0522e) */
/* WARNING: Removing unreachable block (ram,0x10f052e6) */
/* WARNING: Could not reconcile some variable overlaps */

undefined2 __cdecl16far
BATTLE::DpFromPtokBrcToBrc(TOK *ptok,byte brcSrc,byte brcTarget,TOK *ptokTarget,int fProximity)

{
  int iVar1;
  long lVar2;
  bool bVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  int iVar7;
  int iVar8;
  short *psVar9;
  undefined2 uVar10;
  SHDEF *pSVar11;
  ulong uVar12;
  ulong uVar13;
  long lVar14;
  undefined4 uVar15;
  long lVar16;
  undefined2 uVar17;
  undefined2 uVar18;
  undefined2 uVar19;
  undefined2 uVar20;
  undefined2 uVar21;
  undefined2 uVar22;
  undefined4 uVar23;
  long dpShieldsLeft;
  PART part;
  long dp;
  long cTorpHit;
  HUL *lphul;
  long dRange;
  short fOutOfRange;
  long dpTotal;
  long cTorpBase;
  short ihs;
  long dpShdef;
  long dpMax;
  short dz;
  
  uVar4 = DzFromBrcBrc(brcSrc,brcTarget);
  lVar2 = 0;
  if ((fProximity == 0) && ((int)(*(uint *)((int)ptok + 0x19) & 0xf) < (int)uVar4)) {
    dpTotal._0_2_ = 0;
  }
  else {
    pSVar11 = LpshdefFromTok(ptok);
    ihs = 0;
    while( true ) {
      dpTotal._0_2_ = (undefined2)lVar2;
      uVar10 = (undefined2)((ulong)pSVar11 >> 0x10);
      iVar8 = (int)pSVar11;
      if ((int)(uint)*(byte *)(iVar8 + 0x7a) <= ihs) break;
      if (((*(uint *)(iVar8 + 0x3a + ihs * 4) & 0x30) != 0) &&
         (*(uint *)(iVar8 + ihs * 4 + 0x3c) >> 8 != 0)) {
        psVar9 = (short *)(iVar8 + 0x3a + ihs * 4);
        part.hs.grhst = *psVar9;
        part.hs.flags2 = psVar9[1];
        _DATA::idPlayer = (int)*(byte *)((int)ptok + 2);
        PARTS::FLookupPart(&part);
        _DATA::idPlayer = -1;
        uVar10 = (undefined2)((ulong)part.pterra >> 0x10);
        uVar6 = (uint)(*(char *)((int)ptok + 3) == '\x01') + *(int *)((int)part.pterra + 0x34);
        iVar8 = (int)uVar6 >> 0xf;
        iVar7 = (int)uVar4 >> 0xf;
        if ((iVar7 < iVar8) || ((iVar7 <= iVar8 && (uVar4 <= uVar6)))) {
          bVar3 = false;
        }
        else {
          bVar3 = true;
        }
        if ((!bVar3) || (fProximity != 0)) {
          iVar1 = *(int *)((int)part.pterra + 0x36);
          uVar12 = PUBLIC::__aFulmul(iVar1,iVar1 >> 0xf,(uint)part.hs.flags2 >> 8,0);
          if (part.hs.grhst == 0x10) {
            if (*(char *)((int)ptok + 0xd) != '\0') {
              uVar23 = 100;
              uVar15 = PUBLIC::__aFulmul(uVar12,*(undefined *)((int)ptok + 0xd),0);
              uVar12 = PUBLIC::__aFldiv(uVar15,uVar23);
            }
            if (((0 < (int)uVar4) && (-1 < iVar8)) && ((0 < iVar8 || (uVar6 != 0)))) {
              lVar14 = (long)(int)uVar6;
              uVar17 = 0;
              uVar10 = 10;
              uVar15 = PUBLIC::__aFulmul(uVar12,uVar4,iVar7);
              uVar15 = PUBLIC::__aFldiv(uVar15,uVar10,uVar17);
              lVar14 = PUBLIC::__aFldiv(uVar15,lVar14);
              uVar12 = uVar12 - lVar14;
            }
            if (*(byte *)((int)ptokTarget + 0xe) < 100) {
              uVar23 = 100;
              uVar15 = PUBLIC::__aFulmul(uVar12,*(undefined *)((int)ptokTarget + 0xe),0);
              uVar12 = PUBLIC::__aFldiv(uVar15,uVar23);
            }
            if (((*(uint *)((int)part.pterra + 0x3a) & 1) != 0) &&
               (uVar13 = PUBLIC::__aFulmul(*(undefined2 *)((int)ptokTarget + 0x11),0,
                                           *(undefined2 *)((int)ptok + 0x13),0),
               (long)uVar13 < (long)uVar12)) {
              uVar12 = uVar13;
            }
            if (bVar3) {
              uVar5 = uVar4 + 10;
              uVar12 = PUBLIC::__aFldiv(uVar12,uVar5 - uVar6,
                                        (((int)uVar5 >> 0xf) - iVar8) - (uint)(uVar5 < uVar6));
              if (((long)uVar12 < 0x10000) &&
                 (((long)uVar12 < 0 || ((uint)uVar12 < (uint)part.hs.flags2 >> 8)))) {
                uVar12 = (ulong)((uint)part.hs.flags2 >> 8);
              }
            }
            lVar14 = PUBLIC::__aFulmul(uVar12,*(undefined2 *)((int)ptok + 0x13),0);
            lVar2 = lVar14 + lVar2;
          }
          else if (part.hs.grhst == 0x20) {
            uVar23 = 200;
            uVar15 = PUBLIC::__aFulmul((uint)part.hs.flags2 >> 8,0,*(undefined2 *)((int)ptok + 0x13)
                                       ,0);
            lVar14 = PUBLIC::__aFulmul(uVar15,uVar23);
            uVar17 = (undefined2)((ulong)lVar14 >> 0x10);
            uVar10 = CTorpHit(lVar14,(int)ptokTarget,ptokTarget._2_2_,
                              *(undefined2 *)((int)part.pterra + 0x3a));
            uVar23 = 200;
            iVar7 = *(int *)((int)part.pterra + 0x36);
            uVar15 = PUBLIC::__aFulmul(iVar7,iVar7 >> 0xf,uVar10,uVar17);
            uVar12 = PUBLIC::__aFldiv(uVar15,uVar23);
            if (*(int *)((int)ptokTarget + 0x11) != 0) {
              uVar23 = 0x640;
              iVar7 = *(int *)((int)part.pterra + 0x36);
              uVar15 = PUBLIC::__aFulmul(lVar14 - CONCAT22(uVar17,uVar10),iVar7,iVar7 >> 0xf);
              lVar14 = PUBLIC::__aFldiv(uVar15,uVar23);
              uVar12 = uVar12 + lVar14;
            }
            if (bVar3) {
              uVar5 = uVar4 + 10;
              uVar12 = PUBLIC::__aFldiv(uVar12,uVar5 - uVar6,
                                        (((int)uVar5 >> 0xf) - iVar8) - (uint)(uVar5 < uVar6));
              if (((long)uVar12 < 0x10000) &&
                 (((long)uVar12 < 0 || ((uint)uVar12 < (uint)part.hs.flags2 >> 8)))) {
                uVar12 = (ulong)((uint)part.hs.flags2 >> 8);
              }
            }
            lVar2 = uVar12 + lVar2;
          }
        }
      }
      ihs = ihs + 1;
    }
    pSVar11 = LpshdefFromTok(ptokTarget);
    uVar4 = *(uint *)((int)pSVar11 + 0x38);
    uVar6 = *(uint *)((int)ptokTarget + 0x11);
    lVar14 = PUBLIC::__aFulmul(uVar6 + uVar4,CARRY2(uVar6,uVar4),
                               *(undefined2 *)((int)ptokTarget + 0x13),0);
    if ((*(int *)((int)ptokTarget + 0x15) != 0) && (0 < lVar14)) {
      uVar23 = 500;
      uVar10 = *(undefined2 *)((int)ptokTarget + 0x13);
      uVar22 = 0;
      uVar21 = 0;
      uVar20 = 10;
      uVar6 = *(uint *)((int)ptokTarget + 0x15) & 0x7f;
      uVar19 = 0;
      uVar18 = 0;
      uVar17 = 10;
      uVar15 = PUBLIC::__aFulmul(uVar4,0,*(uint *)((int)ptokTarget + 0x15) >> 7,0);
      uVar15 = PUBLIC::__aFldiv(uVar15,uVar17,uVar18);
      uVar15 = PUBLIC::__aFulmul(uVar15,uVar6,uVar19);
      uVar15 = PUBLIC::__aFldiv(uVar15,uVar20,uVar21);
      uVar15 = PUBLIC::__aFulmul(uVar15,uVar10,uVar22);
      lVar16 = PUBLIC::__aFldiv(uVar15,uVar23);
      lVar14 = lVar14 - lVar16;
      if (lVar14 < 1) {
        lVar14 = 1;
      }
    }
    dpMax._0_2_ = (undefined2)lVar14;
    if ((lVar14 < lVar2) && (fProximity == 0)) {
      dpTotal._0_2_ = (undefined2)dpMax;
    }
  }
  return (undefined2)dpTotal;
}



// ======================================================================
// Function: DpShieldOfShdef
// Address: 1038:0f24
// ======================================================================


/* WARNING: Removing unreachable block (ram,0x103810d2) */
/* WARNING: Could not reconcile some variable overlaps */

undefined2 __cdecl16far UTIL::DpShieldOfShdef(int lpshdef,undefined2 param_2,int iplr)

{
  byte bVar1;
  long lVar2;
  uint uVar3;
  short sVar4;
  undefined2 uVar5;
  int iVar6;
  bool bVar7;
  long lVar8;
  undefined2 uVar9;
  undefined2 uVar10;
  PART part;
  HUL *lphul;
  long dpShdef;
  short ihs;
  HS *lphs;
  short chs;
  
  dpShdef._0_2_ = 0;
  dpShdef._2_2_ = 0;
  lphs = (HS *)CONCAT22(param_2,lpshdef + 0x3a);
  bVar1 = *(byte *)(lpshdef + 0x7a);
  for (ihs = 0; lVar2 = CONCAT22(dpShdef._2_2_,(uint)dpShdef), ihs < (int)(uint)bVar1; ihs = ihs + 1
      ) {
    iVar6 = (int)lphs;
    uVar5 = (undefined2)((ulong)lphs >> 0x10);
    if ((lphs->grhst == 4) && (*(uint *)(iVar6 + 2) >> 8 != 0)) {
      part.hs.grhst = lphs->grhst;
      part.hs.flags2 = *(short *)(iVar6 + 2);
      PARTS::FLookupPart(&part);
      uVar3 = *(int *)((int)part.pterra + 0x34) * (*(uint *)(iVar6 + 2) >> 8);
      bVar7 = CARRY2((uint)dpShdef,uVar3);
      dpShdef._0_2_ = (uint)dpShdef + uVar3;
      dpShdef._2_2_ = dpShdef._2_2_ + (uint)bVar7;
    }
    else if (((lphs->grhst == 8) && (*(uint *)(iVar6 + 2) >> 8 != 0)) &&
            ((*(uint *)(iVar6 + 2) & 0xff) == 6)) {
      uVar3 = (*(uint *)(iVar6 + 2) >> 8) * 0x32;
      bVar7 = CARRY2((uint)dpShdef,uVar3);
      dpShdef._0_2_ = (uint)dpShdef + uVar3;
      dpShdef._2_2_ = dpShdef._2_2_ + (uint)bVar7;
    }
    else if ((lphs->grhst == 8) && ((*(uint *)(iVar6 + 2) & 0xff) == 9)) {
      uVar3 = (*(uint *)(iVar6 + 2) >> 8) * 100;
      bVar7 = CARRY2((uint)dpShdef,uVar3);
      dpShdef._0_2_ = (uint)dpShdef + uVar3;
      dpShdef._2_2_ = dpShdef._2_2_ + (uint)bVar7;
    }
    lphs = (HS *)CONCAT22(uVar5,iVar6 + 4);
  }
  sVar4 = RACE::GetRaceGrbit((PLAYER *)((int)&c_common::rgplr + iplr * 0xc0),0xd);
  if (sVar4 != 0) {
    uVar10 = 0;
    uVar9 = 5;
    uVar5 = PUBLIC::__aFlshl(5,0);
    lVar8 = PUBLIC::__aFldiv(uVar5,dpShdef._2_2_,uVar9,uVar10);
    lVar2 = lVar8 + lVar2;
  }
  dpShdef._2_2_ = (int)((ulong)lVar2 >> 0x10);
  dpShdef._0_2_ = (uint)lVar2;
  if (dpShdef._2_2_ != 0) {
    dpShdef._0_2_ = 0xffff;
  }
  return (uint)dpShdef;
}



